version: "3.9"

services:

  webapp:
    image: build
    build:
      context: ./TodoApi/
      dockerfile: Dockerfile.yml
    ports:
      - 8000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080    
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: todos
    ports:
      - 5432:5432
