name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore .NET dependencies
      run: dotnet restore ./TodoApi/TodoApi/TodoApi.csproj

    - name: Build .NET Web API
      run: dotnet build ./TodoApi/TodoApi/TodoApi.csproj --configuration Release --no-restore        
          
  deploy:
    runs-on: ubuntu-latest
    name: Checkout code
    uses: actions/checkout@v4
    
    - name: Copy files to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 146.59.18.101 >> ~/.ssh/known_hosts
        rsync -avz --delete ./ ubuntu>@<146.59.18.101:/var/www/html/