name: Build solution

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore .NET dependencies
      run: dotnet restore ./TodoApi/TodoApi/TodoApi.csproj

    - name: Build .NET Web API
      run: dotnet build ./TodoApi/TodoApi/TodoApi.csproj --configuration Release --no-restore        