on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore .NET dependencies
      run: dotnet restore ./TodoApi/TodoApi/TodoApi.csproj

    - name: Build .NET Web API
      run: dotnet build ./TodoApi/TodoApi/TodoApi.csproj --configuration Release --no-restore        

  deploy:
    runs-on: ubuntu-latest
    name: Deploy my nice code
    steps:
    - name: Deploy to OVH hosting
      uses: pitscher/ovh-deploy-hosting-action@v1
      env:
        OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
        OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
        OVH_HOSTING_DOMAIN: vps-5f245e44.vps.ovh.net
        REPOSITORY_NAME: todo-app
        REPOSITORY_URL: https://github.com/mrcombajn/todo-app.git