name: Deploy to VPS

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 146.59.18.101 >> ~/.ssh/known_hosts
        rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./TodoApi/ ubuntu@146.59.18.101:/var/server/ << 'EOF'
            set -e
            cd ~/var/server/
            docker compose up -d --build --force-recreate --no-deps
        EOF